### ISSUE TITLE
everything undefined?

### ISSUE THREAD

**Issue by mmattbtw** [GNosii/c2d#3]
<img width="477" alt="image" src="https://user-images.githubusercontent.com/30363562/190927993-7afb4da4-fdae-4eef-8296-7167d9476ae4.png">
<img width="826" alt="image" src="https://user-images.githubusercontent.com/30363562/190927999-6af7f4c4-5de0-4033-8c94-4303fd9015e1.png">

I just have the default payload, so I don't know if I'm doing anything wrong or what because everything is undefined :p

**Comment by GNosii** [comment]
I'm planning on rewriting this entire thing, sorry, did you get it working?

**Comment by mmattbtw** [comment]
nope @GNosii 
![image](https://user-images.githubusercontent.com/30363562/201260352-bb71de42-5031-425c-addf-e69b3476765b.png)

**Comment by GNosii** [comment]
Do you have the 'Batch Webhook' option on? If not, try enabling it.

**Comment by mmattbtw** [comment]
yes i do :p

**Comment by GNosii** [comment]
I rewrote this entire thing, here you can see the repo for the new version: https://github.com/GNosii/crowdis

**Comment by mmattbtw** [comment]
@GNosii lmk when you document how to set it  up :-)

**Comment by GNosii** [comment]
> @GNosii lmk when you document how to set it up :-)
Talk to me through Discord, I'm currently getting it as stable as possible, it's not really meant for production use. Amaritopd#4515
